/**
 * Permission constants — mirrors backend Permission enum.
 * Used with usePermissions() hook and PermissionGate component.
 */
export const P = {
  DASHBOARD_VIEW:   'DASHBOARD_VIEW',

  INBOUND_VIEW:     'INBOUND_VIEW',
  INBOUND_RECEIVE:  'INBOUND_RECEIVE',

  INVENTORY_VIEW:   'INVENTORY_VIEW',
  INVENTORY_ADJUST: 'INVENTORY_ADJUST',

  PUTAWAY_VIEW:     'PUTAWAY_VIEW',
  PUTAWAY_EXECUTE:  'PUTAWAY_EXECUTE',

  PICKING_VIEW:     'PICKING_VIEW',
  PICKING_EXECUTE:  'PICKING_EXECUTE',

  PACKING_VIEW:     'PACKING_VIEW',
  PACKING_EXECUTE:  'PACKING_EXECUTE',

  SHIPPING_VIEW:    'SHIPPING_VIEW',
  SHIPPING_CONFIRM: 'SHIPPING_CONFIRM',

  ORDERS_VIEW:      'ORDERS_VIEW',
  ORDERS_CREATE:    'ORDERS_CREATE',

  TROLLEYS_VIEW:    'TROLLEYS_VIEW',
  TROLLEYS_CREATE:  'TROLLEYS_CREATE',
  TROLLEYS_ASSIGN:  'TROLLEYS_ASSIGN',

  LABELS_VIEW:      'LABELS_VIEW',
  LABELS_PRINT:     'LABELS_PRINT',

  REPORTS_VIEW:     'REPORTS_VIEW',
  REPORTS_EXPORT:   'REPORTS_EXPORT',

  MASTER_VIEW:      'MASTER_VIEW',
  MASTER_MANAGE:    'MASTER_MANAGE',

  USERS_VIEW:       'USERS_VIEW',
  USERS_MANAGE:     'USERS_MANAGE',
};

/**
 * Permission matrix for documentation/UI display.
 * Mirrors backend Role enum definitions.
 */
export const ROLE_PERMISSIONS = {
  SUPER_ADMIN: Object.values(P),
  ADMIN: [
    P.DASHBOARD_VIEW,
    P.INBOUND_VIEW,    P.INBOUND_RECEIVE,
    P.INVENTORY_VIEW,  P.INVENTORY_ADJUST,
    P.PUTAWAY_VIEW,    P.PUTAWAY_EXECUTE,
    P.PICKING_VIEW,    P.PICKING_EXECUTE,
    P.PACKING_VIEW,    P.PACKING_EXECUTE,
    P.SHIPPING_VIEW,   P.SHIPPING_CONFIRM,
    P.ORDERS_VIEW,     P.ORDERS_CREATE,
    P.TROLLEYS_VIEW,   P.TROLLEYS_CREATE,  P.TROLLEYS_ASSIGN,
    P.LABELS_VIEW,     P.LABELS_PRINT,
    P.REPORTS_VIEW,    P.REPORTS_EXPORT,
    P.MASTER_VIEW,     P.MASTER_MANAGE,
    P.USERS_VIEW,
  ],
  MANAGER: [
    P.DASHBOARD_VIEW,
    P.INBOUND_VIEW,    P.INBOUND_RECEIVE,
    P.INVENTORY_VIEW,  P.INVENTORY_ADJUST,
    P.PUTAWAY_VIEW,    P.PUTAWAY_EXECUTE,
    P.PICKING_VIEW,    P.PICKING_EXECUTE,
    P.PACKING_VIEW,    P.PACKING_EXECUTE,
    P.SHIPPING_VIEW,   P.SHIPPING_CONFIRM,
    P.ORDERS_VIEW,     P.ORDERS_CREATE,
    P.TROLLEYS_VIEW,   P.TROLLEYS_CREATE,  P.TROLLEYS_ASSIGN,
    P.LABELS_VIEW,     P.LABELS_PRINT,
    P.REPORTS_VIEW,    P.REPORTS_EXPORT,
    P.MASTER_VIEW,
  ],
  WORKER: [
    P.DASHBOARD_VIEW,
    P.INBOUND_VIEW,
    P.INVENTORY_VIEW,
    P.PUTAWAY_VIEW,    P.PUTAWAY_EXECUTE,
    P.PICKING_VIEW,    P.PICKING_EXECUTE,
    P.PACKING_VIEW,    P.PACKING_EXECUTE,
    P.TROLLEYS_VIEW,   P.TROLLEYS_CREATE,  P.TROLLEYS_ASSIGN,
    P.LABELS_VIEW,     P.LABELS_PRINT,
  ],
};

export const ROLES = ['SUPER_ADMIN', 'ADMIN', 'MANAGER', 'WORKER'];
